<?php 
    $errors = [];
    $errorMessage = '';

    if (!empty($_POST)) {
        $firstname = $_POST['firstname'];
        $lastname = $_POST['lastname'];
        $email = $_POST['email'];
        $message = $_POST['message'];

        if (empty($firstname)) {
            $errors[] = 'firstname is empty';
        }

        if (empty($lastname)) {
            $errors[] = 'lastname is empty';
        }

        if (empty($email)) {
            $errors[] = 'Email is empty';
        } else if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $errors[] = 'Email is invalid';
        }

        if (empty($message)) {
            $errors[] = 'Message is empty';
        }

        if (empty($errors)) {
            $toEmail = 'info@secureattestation.com';
            $date = date('Y/m/d H:i:s');
            $emailSubject = "SecureAttestation has new enquiry at {$date}";
            $headers = ['From' => $email, 'Reply-To' => $email, 'Content-type' => 'text/html; charset=utf-8', 'MIME-Version' => '1.0'];
            $bodyParagraphs = "<p>Below is the enquiry from {$firstname} {$lastname}<p> <br>";
            $bodyParagraphs .= "<p>{$message}</p> <br>";
            $bodyParagraphs .= "<p> This is an autogenerated email generated for the enquiry from the website ";
            $bodyParagraphs .= '<a href="www.secureattestation.com" target=_blank>www.secureattestation.com</a> requires immediate attention.';
            // $body = join(PHP_EOL, $bodyParagraphs);
            mail($toEmail, $emailSubject, $bodyParagraphs, $headers);
            //if (mail($toEmail, $emailSubject, $bodyParagraphs, $headers)) {
                //header('Location: ' . '/SecureAttestation/index.html?msg=Secure Attestation team will process your enquiry and will get back with details soon', true, 301);

            //} else {
                //header('Location: ' . '/SecureAttestation/index.html?error', true, 301);
            //}
        }

   } else {

       $allErrors = join('<br/>', $errors);
       $errorMessage = "<p style='color: red;'>{$allErrors}</p>";
   }

?>